### ISSUE TITLE
WebGL fullscreen cannot work, unity 2022.3.20 LTS

### ISSUE THREAD

**Issue by zaichenhu** [kou-yeung/WebGLInput#138] opened 2024-05-07 09:54 UTC
I noticed you have had some recent updates, and I'm not sure if one of the issues I previously raised (#134) has been addressed. There has been an ongoing problem in the 2022.3.x version where I couldn't input Chinese characters while in full-screen mode（Full-screen mode without the white bar at the top.）I have tested it in firefox, google chrome and edge on windows10

![TestIME3](https://github.com/kou-yeung/WebGLInput/assets/59084679/363291e7-fd46-481c-a6e6-50d7bd5e93b9)

**Comment by kou-yeung** [comment] 2024-05-11 03:17
release a new version for fullscreen.
[release](https://github.com/kou-yeung/WebGLInput/releases/tag/1.3.3)

you can call WebGLSupport.WebGLWindow.SwitchFullscreen() from your app to switch fullscreen.

**Comment by zaichenhu** [comment] 2024-05-14 03:23
> release a new version for fullscreen. [release](https://github.com/kou-yeung/WebGLInput/releases/tag/1.3.3)
> 
> you can call WebGLSupport.WebGLWindow.SwitchFullscreen() from your app to switch fullscreen.

I encountered an issue where I don't know how to call this method when clicking on Unity's default template fullscreen. So, this method should be called within the game to switch to fullscreen effectively.

**Comment by kou-yeung** [comment] 2024-05-14 13:50
on Unity's default template fullscreen button.
it was call "unityInstance.SetFullscreen(1);" to make fullscreen for canvas.

i tried eidt the index.html ( unity 2023.2.2f1 ) Line.106

```
unityInstance.SetFullscreen(1);
↓
document.makeFullscreen("unity-container");
```
the default fullscreen button is work.

**Comment by kou-yeung** [comment] 2024-05-14 13:58
and i tried Unity's minimal default template.
in this time . WebGLSupport.WebGLWindow.SwitchFullscreen() is not work for this.

because  minimal default template was like ↓
```
<body>
  <canvas />
</body>
```
document.makeFullscreen() is add a new div element to parentNode of canvas. ( in this case is the <body> )
the <body> element can not add to other element...


e.g. in Unity's default template

non fullscreen mode : 
```
<body>
  <div id="unity-container" class="unity-desktop">
    <canvas id="unity-canvas" width=960 height=600 tabindex="-1"></canvas>
  </div>
</body>
```
when called WebGLSupport.WebGLWindow.SwitchFullscreen()
```
<body>
  <div>  // <-- add a new div element and make it to fullscreeen
    <div id="unity-container" class="unity-desktop">
      <canvas id="unity-canvas" width=960 height=600 tabindex="-1"></canvas>
    </div>
  </div>
</body>
```

**Comment by kou-yeung** [comment] 2024-05-14 13:59
i think can check the canvas parentNode type and switch it...
but i need same time to test it..

**Comment by kou-yeung** [comment] 2024-05-14 14:45
release a new version for minimal default template
https://github.com/kou-yeung/WebGLInput/releases/tag/1.3.5

**Comment by kou-yeung** [comment] 2024-05-14 15:28
update README demo link use github io.
build with all Unity's WebGL Template. ^^

**Comment by kou-yeung** [comment] 2024-05-14 22:08
i will try to overwrite the default fullscreen button after build.
https://github.com/kou-yeung/WebGLInput/issues/146

**Comment by kou-yeung** [comment] 2024-05-15 11:53
release a new version~
https://github.com/kou-yeung/WebGLInput/releases/tag/1.3.6

**Comment by zaichenhu** [comment] 2024-05-16 10:13
> release a new version~ https://github.com/kou-yeung/WebGLInput/releases/tag/1.3.6

I have tested it on Chrome, Firefox, Edge, and Safari, and now it can all be input correctly. This is great! Thank you very much.

**Comment by kou-yeung** [comment] 2024-05-16 10:24
`I have a small suggestion, Could you please adjust the position of the suggestion box more reasonably? Sometimes it appears at the top of the screen, and other times it may cover the input box, especially when using Safari.`

can i has a reproduction project. and create a new isuue to me.
because this was dependent with font size, <input> element size and unity inputfiled rect..

**Comment by kou-yeung** [comment] 2024-05-16 10:24
so, i will close this issue~
thanks!

**Closed** 2024-05-17 01:48 UTC
Labels: verification scheduled, fullscreen
